name: Validate definitions

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  test definitions:
    name: Validate definitions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python üêç
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Run Validations
        uses: ./.github/workflows/validation-template.yaml
